// ********RoostGPT********
/*
Test generated by RoostGPT for test bankingportal using AI Type DBRX and AI Model meta-llama-3-70b-instruct-041824
ROOST_METHOD_HASH=setGeneratedAt_be03f4078a
ROOST_METHOD_SIG_HASH=setGeneratedAt_acf2df6eda
Here are the generated test scenarios for the `setGeneratedAt` method:
**Scenario 1: Set GeneratedAt with valid LocalDateTime**
Details:
  TestName: setGeneratedAtWithValidLocalDateTime
  Description: Verifies that the `setGeneratedAt` method sets the `generatedAt` field with a valid `LocalDateTime` object.
Execution:
  Arrange: Create a valid `LocalDateTime` object.
  Act: Call the `setGeneratedAt` method with the valid `LocalDateTime` object.
  Assert: Verify that the `generatedAt` field is set to the expected value using `assertEquals`.
Validation:
  The assertion aims to verify that the `setGeneratedAt` method correctly sets the `generatedAt` field. This test ensures that the method behaves as expected when provided with a valid input, which is essential for the application's business logic.
**Scenario 2: Set GeneratedAt with null LocalDateTime**
Details:
  TestName: setGeneratedAtWithNullLocalDateTime
  Description: Verifies that the `setGeneratedAt` method sets the `generatedAt` field to null when provided with a null `LocalDateTime` object.
Execution:
  Arrange: Create a null `LocalDateTime` object.
  Act: Call the `setGeneratedAt` method with the null `LocalDateTime` object.
  Assert: Verify that the `generatedAt` field is set to null using `assertNull`.
Validation:
  The assertion aims to verify that the `setGeneratedAt` method correctly sets the `generatedAt` field to null when provided with a null input. This test ensures that the method behaves as expected when handling null inputs, which is essential for preventing `NullPointerExceptions` in the application.
**Scenario 3: Set GeneratedAt with same LocalDateTime object**
Details:
  TestName: setGeneratedAtWithSameLocalDateTimeObject
  Description: Verifies that the `setGeneratedAt` method sets the `generatedAt` field to the same `LocalDateTime` object when provided with the same object.
Execution:
  Arrange: Create a valid `LocalDateTime` object.
  Act: Call the `setGeneratedAt` method with the same `LocalDateTime` object.
  Assert: Verify that the `generatedAt` field is set to the same object using `assertSame`.
Validation:
  The assertion aims to verify that the `setGeneratedAt` method correctly sets the `generatedAt` field to the same object when provided with the same input. This test ensures that the method behaves as expected when handling identical inputs, which is essential for maintaining the application's state consistency.
Note that these test scenarios cover the basic functionality of the `setGeneratedAt` method, including edge cases and error handling.
*/
// ********RoostGPT********
package com.webapp.bankingportal.entity;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import java.time.LocalDateTime;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import org.junit.jupiter.api.*;

@Tag("com.webapp.bankingportal.entity")
@Tag("com.webapp.bankingportal.entity.setGeneratedAt")
public class OtpInfoSetGeneratedAtTest {
    @Test
    public void setGeneratedAtWithValidLocalDateTime() {
        // Arrange
        OtpInfo otpInfo = new OtpInfo();
        LocalDateTime validGeneratedAt = LocalDateTime.now();
        // Act
        otpInfo.setGeneratedAt(validGeneratedAt);
        // Assert
        assertEquals(validGeneratedAt, otpInfo.getGeneratedAt());
    }
    @Test
    public void setGeneratedAtWithNullLocalDateTime() {
        // Arrange
        OtpInfo otpInfo = new OtpInfo();
        LocalDateTime nullGeneratedAt = null;
        // Act
        otpInfo.setGeneratedAt(nullGeneratedAt);
        // Assert
        assertNull(otpInfo.getGeneratedAt());
    }
    @Test
    public void setGeneratedAtWithSameLocalDateTimeObject() {
        // Arrange
        OtpInfo otpInfo = new OtpInfo();
        LocalDateTime sameGeneratedAt = LocalDateTime.now();
        // Act
        otpInfo.setGeneratedAt(sameGeneratedAt);
        // Assert
        assertSame(sameGeneratedAt, otpInfo.getGeneratedAt());
    }
}